services:
  polyocr:
    build:
      context: .
    volumes:
      - ./datasets:/app/datasets
      - ./results:/app/results
    command: >
      python cli.py
      --dataset datasets/eng
      --lang eng
      --engines easyocr,doctr
      